version: '3'

tasks:
  default:
    desc: Run the default task (serve)
    cmds:
      - task: run

  init:
    desc: Initialize project environment
    cmds:
      - git init
      - uv init .
      - uv add --dev ruff
      - git add .
      - git commit -m "init"

  fmt:
    desc: Format code
    cmds:
      - uv run ruff format .

  lint:
    desc: Lint code
    cmds:
      - uv run ruff check . --fix

  serve:
    desc: Serve the application locally (MkDocs)
    cmds:
      - uv run mkdocs serve -a localhost:8080

  build:
    desc: Build the static site
    cmds:
      - uv run mkdocs build

  run:
    desc: Run the application
    cmds:
      - task: serve
