version: '3'

tasks:
  default:
    cmds:
      - task: dev

  dev:
    desc: "Start development server"
    cmds:
      - uv run mkdocs serve -a localhost:8080

  build:
    desc: "Build static site"
    cmds:
      - uv run mkdocs build --strict

  deploy:
    desc: "Deploy to GitHub Pages"
    cmds:
      - uv run mkdocs gh-deploy --force --clean

  fix:
    desc: "Auto-fix code, format, and assets (Destructive)"
    cmds:
      - npx ts-node src/main.ts fix

  check:
    desc: "Run all checks and audits (Read-only)"
    cmds:
      - npx ts-node src/main.ts audit
      - uv run mkdocs build --strict

  init:
    desc: "Initialize project environment"
    cmds:
      - git init
      - npm install
      - uv init .
      - uv add mkdocs mkdocs-material
      - git add .
      - git commit -m "init"
