version: '3'

tasks:
  default:
    cmds:
      - task: serve

  init:
    cmds:
      - git init
      - uv init .
      - uv add --dev ruff
      - uv add pyyaml pydantic requests
      - git add .
      - git commit -m "init"

  fmt:
    cmds:
      - uv run ruff format .

  lint:
    cmds:
      - uv run ruff check . --fix

  scripts:links:
    cmds:
      - uv run scripts/maintain.py add-links

  scripts:check:
    cmds:
      - uv run scripts/maintain.py check-links

  scripts:cards:
    cmds:
      - uv run scripts/maintain.py sync-cards

  serve:
    cmds:
      - uv run mkdocs serve -a localhost:8080

  build:
    cmds:
      - uv run mkdocs build

  deploy:
    cmds:
      - uv run mkdocs gh-deploy --force
