version: '3'

tasks:
  default:
    cmds:
      - task: dev

  dev:
    desc: "Start development server"
    cmds:
      - uv run mkdocs serve -a localhost:8080

  build:
    desc: "Build static site"
    cmds:
      - uv run mkdocs build --strict

  deploy:
    desc: "Deploy to GitHub Pages"
    cmds:
      - uv run mkdocs gh-deploy --force --clean

  fix:
    desc: "Auto-fix code, format, and assets (Destructive)"
    cmds:
      - uv run ruff check . --fix
      - uv run ruff format .
      - uv run scripts/maintain.py add-links
      - uv run scripts/maintain.py sync-cards
      - uv run scripts/maintain.py download-assets
      - uv run scripts/maintain.py add-anchors

  check:
    desc: "Run all checks and audits (Read-only)"
    cmds:
      - uv run ruff check .
      - uv run ruff format . --check
      - uv run scripts/maintain.py audit
      - uv run mkdocs build --strict

  init:
    desc: "Initialize project environment"
    cmds:
      - git init
      - uv init .
      - uv add --dev ruff
      - uv add pyyaml pydantic requests mkdocs mkdocs-material
      - git add .
      - git commit -m "init"
